module.exports = {
  DEFAULT_REQUEST_TIMEOUT : 10000,
  DEFAULT_PULL_INTERVALL_SECONDS : 300,
  DEFAULT_BATTERY_FULL_PERCENTAGE: 95,
  DEFAULT_BATTERY_FULL_TIME_TO_SWITCH_IN_MINUTES:5,
  DEFAULT_SURPLUS_POWER_MINIMUM_WATT_TO_SELL:1000,
  DEFAULT_SURPLUS_POWER_TIME_TO_SWITCH_IN_MINUTES:5,
  DEFAULT_SURPLUS_POWER_ONLY_WHEN_BATTERY_FULL: false
};